import { GuestDefinition, GuestType } from "./types";

// ============================================================
// Guest Definitions – reference data for every guest archetype
// ============================================================

export const GUEST_DEFINITIONS: Record<GuestType, GuestDefinition> = {
  // --- Default guests ---
  old_friend: {
    type: "old_friend",
    name: "Old Friend",
    shopCost: 2,
    basePopularity: 1,
    baseCash: 0,
    ability: null,
    isStar: false,
    maxCopies: 4,
    color: "#6B8CFF",
  },
  rich_pal: {
    type: "rich_pal",
    name: "Rich Pal",
    shopCost: 3,
    basePopularity: 0,
    baseCash: 1,
    ability: null,
    isStar: false,
    maxCopies: 4,
    color: "#4ADE80",
  },
  wild_buddy: {
    type: "wild_buddy",
    name: "Wild Buddy",
    shopCost: 0, // Cannot be purchased
    basePopularity: 2,
    baseCash: 0,
    ability: "trouble",
    isStar: false,
    maxCopies: 0, // Always exactly 4, not purchasable
    color: "#F472B6",
  },

  // --- Non-star purchasable guests ---
  driver: {
    type: "driver",
    name: "Driver",
    shopCost: 3,
    basePopularity: 0,
    baseCash: 0,
    ability: "fetch",
    isStar: false,
    maxCopies: 4,
    color: "#A78BFA",
  },
  private_i: {
    type: "private_i",
    name: "Private I.",
    shopCost: 4,
    basePopularity: 2,
    baseCash: -1,
    ability: "fetch",
    isStar: false,
    maxCopies: 4,
    color: "#818CF8",
  },
  hippy: {
    type: "hippy",
    name: "Hippy",
    shopCost: 4,
    basePopularity: 1,
    baseCash: 0,
    ability: "cancel_trouble",
    isStar: false,
    maxCopies: 4,
    color: "#34D399",
  },
  cute_dog: {
    type: "cute_dog",
    name: "Cute Dog",
    shopCost: 7,
    basePopularity: 2,
    baseCash: 0,
    ability: "cancel_trouble",
    isStar: false,
    maxCopies: 4,
    color: "#FBBF24",
  },
  security: {
    type: "security",
    name: "Security",
    shopCost: 4,
    basePopularity: 0,
    baseCash: 0,
    ability: "boot",
    isStar: false,
    maxCopies: 4,
    color: "#6B7280",
  },
  wrestler: {
    type: "wrestler",
    name: "Wrestler",
    shopCost: 9,
    basePopularity: 2,
    baseCash: 0,
    ability: "boot",
    isStar: false,
    maxCopies: 4,
    color: "#EF4444",
  },
  watch_dog: {
    type: "watch_dog",
    name: "Watch Dog",
    shopCost: 4,
    basePopularity: 2,
    baseCash: 0,
    ability: "peek",
    isStar: false,
    maxCopies: 4,
    color: "#D97706",
  },
  spy: {
    type: "spy",
    name: "Spy",
    shopCost: 8,
    basePopularity: 0,
    baseCash: 2,
    ability: "peek",
    isStar: false,
    maxCopies: 4,
    color: "#1F2937",
  },
  grillmaster: {
    type: "grillmaster",
    name: "Grillmaster",
    shopCost: 5,
    basePopularity: 2,
    baseCash: 0,
    ability: "shuffle",
    isStar: false,
    maxCopies: 4,
    color: "#DC2626",
  },
  athlete: {
    type: "athlete",
    name: "Athlete",
    shopCost: 6,
    basePopularity: 1,
    baseCash: 1,
    ability: "shuffle",
    isStar: false,
    maxCopies: 4,
    color: "#2563EB",
  },
  dancer: {
    type: "dancer",
    name: "Dancer",
    shopCost: 7,
    basePopularity: 0, // Variable – computed at score time
    baseCash: 0,
    ability: "dancer",
    isStar: false,
    maxCopies: 4,
    color: "#EC4899",
  },
  mr_popular: {
    type: "mr_popular",
    name: "Mr. Popular",
    shopCost: 5,
    basePopularity: 3,
    baseCash: 0,
    ability: "bring_one",
    isStar: false,
    maxCopies: 4,
    color: "#F59E0B",
  },
  celebrity: {
    type: "celebrity",
    name: "Celebrity",
    shopCost: 11,
    basePopularity: 2,
    baseCash: 3,
    ability: "bring_two",
    isStar: false,
    maxCopies: 4,
    color: "#FBBF24",
  },
  ticket_taker: {
    type: "ticket_taker",
    name: "Ticket Taker",
    shopCost: 4,
    basePopularity: -1,
    baseCash: 2,
    ability: null,
    isStar: false,
    maxCopies: 4,
    color: "#9CA3AF",
  },
  comedian: {
    type: "comedian",
    name: "Comedian",
    shopCost: 5,
    basePopularity: 0,
    baseCash: -1,
    ability: "comedian",
    isStar: false,
    maxCopies: 4,
    color: "#A855F7",
  },
  photographer: {
    type: "photographer",
    name: "Photographer",
    shopCost: 5,
    basePopularity: 1,
    baseCash: -1,
    ability: "photographer",
    isStar: false,
    maxCopies: 4,
    color: "#64748B",
  },
  caterer: {
    type: "caterer",
    name: "Caterer",
    shopCost: 5,
    basePopularity: 4,
    baseCash: -1,
    ability: null,
    isStar: false,
    maxCopies: 4,
    color: "#F97316",
  },
  auctioneer: {
    type: "auctioneer",
    name: "Auctioneer",
    shopCost: 9,
    basePopularity: 0,
    baseCash: 3,
    ability: null,
    isStar: false,
    maxCopies: 4,
    color: "#7C3AED",
  },
  mascot: {
    type: "mascot",
    name: "Mascot",
    shopCost: 5,
    basePopularity: 1,
    baseCash: 0,
    ability: "mascot",
    isStar: false,
    maxCopies: 4,
    color: "#22D3EE",
  },
  introvert: {
    type: "introvert",
    name: "Introvert",
    shopCost: 4,
    basePopularity: 1,
    baseCash: 0,
    ability: "introvert",
    isStar: false,
    maxCopies: 4,
    color: "#94A3B8",
  },
  stylist: {
    type: "stylist",
    name: "Stylist",
    shopCost: 7,
    basePopularity: 0,
    baseCash: -1,
    ability: "stylist",
    isStar: false,
    maxCopies: 4,
    color: "#E879F9",
  },
  bartender: {
    type: "bartender",
    name: "Bartender",
    shopCost: 11,
    basePopularity: 1,
    baseCash: 0,
    ability: "bartender",
    isStar: false,
    maxCopies: 4,
    color: "#059669",
  },
  writer: {
    type: "writer",
    name: "Writer",
    shopCost: 8,
    basePopularity: 1,
    baseCash: 0,
    ability: "writer",
    isStar: false,
    maxCopies: 4,
    color: "#7C3AED",
  },
  climber: {
    type: "climber",
    name: "Climber",
    shopCost: 12,
    basePopularity: 0, // Starts at 0, increases each appearance
    baseCash: 0,
    ability: "climber",
    isStar: false,
    maxCopies: 4,
    color: "#10B981",
  },
  cheerleader: {
    type: "cheerleader",
    name: "Cheerleader",
    shopCost: 5,
    basePopularity: 1,
    baseCash: 0,
    ability: "cheerleader",
    isStar: false,
    maxCopies: 4,
    color: "#F472B6",
  },
  greeter: {
    type: "greeter",
    name: "Greeter",
    shopCost: 5,
    basePopularity: 1,
    baseCash: 0,
    ability: "greeter",
    isStar: false,
    maxCopies: 4,
    color: "#FBBF24",
  },
  magician: {
    type: "magician",
    name: "Magician",
    shopCost: 5,
    basePopularity: 1,
    baseCash: 0,
    ability: "magician",
    isStar: false,
    maxCopies: 4,
    color: "#8B5CF6",
  },
  cupid: {
    type: "cupid",
    name: "Cupid",
    shopCost: 8,
    basePopularity: 1,
    baseCash: 0,
    ability: "cupid",
    isStar: false,
    maxCopies: 4,
    color: "#FB7185",
  },
  counselor: {
    type: "counselor",
    name: "Counselor",
    shopCost: 7,
    basePopularity: 0,
    baseCash: 0,
    ability: "counselor",
    isStar: false,
    maxCopies: 4,
    color: "#2DD4BF",
  },
  werewolf: {
    type: "werewolf",
    name: "Werewolf",
    shopCost: 5,
    basePopularity: 4,
    baseCash: 0,
    ability: "werewolf",
    isStar: false,
    maxCopies: 4,
    color: "#78716C",
  },
  monkey: {
    type: "monkey",
    name: "Monkey",
    shopCost: 3,
    basePopularity: 4,
    baseCash: 0,
    ability: "trouble",
    isStar: false,
    maxCopies: 4,
    color: "#92400E",
  },
  rock_star: {
    type: "rock_star",
    name: "Rock Star",
    shopCost: 5,
    basePopularity: 3,
    baseCash: 2,
    ability: "trouble",
    isStar: false,
    maxCopies: 4,
    color: "#DC2626",
  },
  gangster: {
    type: "gangster",
    name: "Gangster",
    shopCost: 6,
    basePopularity: 0,
    baseCash: 4,
    ability: "trouble",
    isStar: false,
    maxCopies: 4,
    color: "#1F2937",
  },
  gambler: {
    type: "gambler",
    name: "Gambler",
    shopCost: 7,
    basePopularity: 2,
    baseCash: 3,
    ability: "trouble",
    isStar: false,
    maxCopies: 4,
    color: "#15803D",
  },

  // --- Star guests ---
  alien: {
    type: "alien",
    name: "Alien",
    shopCost: 40,
    basePopularity: 0,
    baseCash: 0,
    ability: null,
    isStar: true,
    maxCopies: 99,
    color: "#22C55E",
  },
  leprechaun: {
    type: "leprechaun",
    name: "Leprechaun",
    shopCost: 50,
    basePopularity: 0,
    baseCash: 3,
    ability: null,
    isStar: true,
    maxCopies: 99,
    color: "#16A34A",
  },
  genie: {
    type: "genie",
    name: "Genie",
    shopCost: 55,
    basePopularity: 0,
    baseCash: 0,
    ability: "fetch",
    isStar: true,
    maxCopies: 99,
    color: "#7C3AED",
  },
  dragon: {
    type: "dragon",
    name: "Dragon",
    shopCost: 30,
    basePopularity: 0,
    baseCash: -3,
    ability: null,
    isStar: true,
    maxCopies: 99,
    color: "#EF4444",
  },
  dinosaur: {
    type: "dinosaur",
    name: "Dinosaur",
    shopCost: 25,
    basePopularity: 0,
    baseCash: 0,
    ability: "trouble",
    isStar: true,
    maxCopies: 99,
    color: "#65A30D",
  },
  mermaid: {
    type: "mermaid",
    name: "Mermaid",
    shopCost: 35,
    basePopularity: 0,
    baseCash: 0,
    ability: "bring_one",
    isStar: true,
    maxCopies: 99,
    color: "#06B6D4",
  },
  ghost: {
    type: "ghost",
    name: "Ghost",
    shopCost: 45,
    basePopularity: 0,
    baseCash: 0,
    ability: "boot",
    isStar: true,
    maxCopies: 99,
    color: "#D1D5DB",
  },
  unicorn: {
    type: "unicorn",
    name: "Unicorn",
    shopCost: 45,
    basePopularity: 0,
    baseCash: 0,
    ability: "cancel_trouble",
    isStar: true,
    maxCopies: 99,
    color: "#F9A8D4",
  },
  superhero: {
    type: "superhero",
    name: "Superhero",
    shopCost: 50,
    basePopularity: 3,
    baseCash: 0,
    ability: null,
    isStar: true,
    maxCopies: 99,
    color: "#2563EB",
  },
};

// ============================================================
// Default rolodex at the start of each scenario
// ============================================================

export interface DefaultRolodexEntry {
  type: GuestType;
  quantity: number;
}

export const DEFAULT_ROLODEX: DefaultRolodexEntry[] = [
  { type: "old_friend", quantity: 4 },
  { type: "rich_pal", quantity: 2 },
  { type: "wild_buddy", quantity: 4 },
];

// ============================================================
// Scenario definitions
// ============================================================

export interface ScenarioDefinition {
  index: number;
  name: string;
  starTypes: [GuestType, GuestType];
  /** Guest types available in the shop for this scenario. */
  availableGuests: GuestType[];
}

/**
 * Placeholder scenarios – in the real game each scenario has a curated pool.
 * We'll flesh these out later; for now each scenario gets all non-star guests.
 */
const ALL_NON_STAR_GUESTS: GuestType[] = Object.values(GUEST_DEFINITIONS)
  .filter((g) => !g.isStar && g.type !== "wild_buddy")
  .map((g) => g.type);

export const SCENARIOS: ScenarioDefinition[] = [
  {
    index: 0,
    name: "Scenario 1",
    starTypes: ["alien", "dinosaur"],
    availableGuests: ALL_NON_STAR_GUESTS,
  },
  {
    index: 1,
    name: "Scenario 2",
    starTypes: ["leprechaun", "dragon"],
    availableGuests: ALL_NON_STAR_GUESTS,
  },
  {
    index: 2,
    name: "Scenario 3",
    starTypes: ["genie", "mermaid"],
    availableGuests: ALL_NON_STAR_GUESTS,
  },
  {
    index: 3,
    name: "Scenario 4",
    starTypes: ["ghost", "unicorn"],
    availableGuests: ALL_NON_STAR_GUESTS,
  },
  {
    index: 4,
    name: "Scenario 5",
    starTypes: ["superhero", "alien"],
    availableGuests: ALL_NON_STAR_GUESTS,
  },
];

// ============================================================
// Game constants
// ============================================================

export const INITIAL_HOUSE_SIZE = 5;
export const MAX_PARTIES_PER_SCENARIO = 25;
export const STARS_REQUIRED = 4;
export const TROUBLE_LIMIT = 3;
export const INITIAL_EXPANSION_COST = 2;
export const MAX_EXPANSION_COST = 12;
export const INITIAL_POPULARITY_CAP = 65;
export const INITIAL_CASH_CAP = 30;
export const UNPAID_GUEST_PENALTY = -7; // Popularity penalty per unpaid guest
